In [ ]:
import torch
torch.__version__

'2.1.0+cu118'

In [ ]:
# torch.Tensor type integer
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# dimensions of a tensor
scalar.ndim

0

In [ ]:
# retrieve the number from the tensor
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

dim 0: 1 element
dim 1: 3 elements
dim 2: 3 elements

In [ ]:
# Creating a random tensor
random_tensor = torch.rand(size = (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3891, 0.9763, 0.9766, 0.1255],
         [0.7381, 0.2178, 0.4379, 0.8741],
         [0.6985, 0.4854, 0.6875, 0.5894]]),
 torch.float32)

In [ ]:
# Creating a tensor to represent an image(size=(244, 244, 3))
random_image_size_tensor = torch.rand(size = (244, 244, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [ ]:
# Creating a tensor of zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Creating a tensor of ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Creating a tensor by specifying start, end, and step
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating a tensor of the same shape
ten_zeros = torch.zeros_like(input = ones)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Creating a tensor of default datatype(float32)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# Creating a tensor of float16
float_16_tensor = torch.tensor([3, 4, 5], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
# Getting information from a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f'shape:{some_tensor.shape}')
print(f'dtype:{some_tensor.dtype}')
print(f'device(GPU or CPU):{some_tensor.device}')

tensor([[0.4906, 0.3783, 0.9517, 0.3053],
        [0.2366, 0.5286, 0.2951, 0.1653],
        [0.5152, 0.0672, 0.9717, 0.8150]])
shape:torch.Size([3, 4])
dtype:torch.float32
device(GPU or CPU):cpu


In [ ]:
# Basic operations to a tensor
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [ ]:
# Using a built in function to perform basic operations
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### speed diference between using loop and using built in function

In [ ]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.55 ms, sys: 25 µs, total: 1.57 ms
Wall time: 4.24 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.23 ms, sys: 10 µs, total: 1.24 ms
Wall time: 1.6 ms


tensor(14)

### Testing shape errors and resolving it

In [ ]:
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
torch.matmul(tensor_A, tensor_B.T) # now the inner dimentions match

tensor([[0.4403, 0.5685],
        [1.2287, 1.1412]])

In [ ]:
# matrix multiplication between an input x and a weights matrix A
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 3,
               out_features = 6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output:
tensor([[ 0.1123,  0.2406,  0.0090,  0.1634,  0.0033,  0.6635],
        [-0.0449,  0.4406,  0.1339, -0.0158,  0.2085,  0.5501]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


### Aggregating tensors

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


In [ ]:
# finding the indices of the max and min values
print(x.argmax())
print(x.argmin())

tensor(9)
tensor(0)


### Changing datatypes of tensors

In [ ]:
tensor = torch.arange(0., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8.dtype

torch.int8

### reshaping, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# changing x with its view z
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# creating a stack of x
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# removing single dimensions
print(x_reshaped.shape)
print(x_reshaped.squeeze().shape)

torch.Size([1, 7])
torch.Size([7])


In [ ]:
# adding a dimension value of 1 at a specific index

x_unsqueezed = x.unsqueeze(dim = 0)
x.shape, x_unsqueezed.shape

(torch.Size([7]), torch.Size([1, 7]))

In [ ]:
# changing shape of a tensor using permute
x_original = torch.rand(size = (224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape, x[0], x[0][0], x[0][0][0]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1] # [2, 5, 8]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1] # 5

tensor([5])

In [ ]:
x[0, 0, :] # [1, 2, 3]

tensor([1, 2, 3])

### Tensors and Numpy

In [ ]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility practice

In [ ]:
# creating two random tensors
random_tensor_A = torch.rand(2, 3)
random_tensor_B = torch.rand(2, 3)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5745, 0.9200, 0.3230],
        [0.8613, 0.0919, 0.3102]])
tensor([[0.9536, 0.6002, 0.0351],
        [0.6826, 0.3743, 0.5220]])
tensor([[False, False, False],
        [False, False, False]])


In [ ]:
# creating tensors with the same flavour
import random

RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(2, 3)

torch.random.manual_seed(seed = RANDOM_SEED)
random_tensor_D = torch.rand(2, 3)

print(random_tensor_C)
print(random_tensor_D)
random_tensor_C == random_tensor_D


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


tensor([[True, True, True],
        [True, True, True]])

### Running tensors on GPUs

In [ ]:
torch.cuda.is_available()

False

In [ ]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# number of GPUs  PyTorch has access to using
torch.cuda.device_count()

1

In [ ]:
# putting a tensor to GPU
tensor = torch.tensor([1, 2, 3])
print(tensor.device)

tensor_gpu = tensor.to(device)
print(tensor_gpu.device)

cpu
cuda:0


In [ ]:
# if a tensor is on GPU, it cannot be converted to a numpy array
tensor_gpu.numpy()

TypeError: ignored

In [ ]:
# copy the tensor on CPU and converting to a numpy array
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Exercises

### 2.Create a random tensor with shape (7, 7)

In [2]:
import torch
tensor = torch.rand(7, 7)
tensor

tensor([[0.9292, 0.1508, 0.8013, 0.2843, 0.4934, 0.3071, 0.5241],
        [0.7443, 0.9787, 0.7225, 0.0628, 0.4020, 0.1370, 0.3369],
        [0.7951, 0.6622, 0.7598, 0.7202, 0.9131, 0.5676, 0.8751],
        [0.3336, 0.6377, 0.0088, 0.9262, 0.3169, 0.0289, 0.2221],
        [0.6869, 0.2803, 0.1226, 0.3762, 0.6286, 0.6147, 0.3570],
        [0.4675, 0.0299, 0.2206, 0.4330, 0.7301, 0.7208, 0.7923],
        [0.0707, 0.7686, 0.6513, 0.2906, 0.0038, 0.7064, 0.5744]])

### 3.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape(1, 7)

In [4]:
tensor1 = torch.rand(1, 7)
torch.matmul(tensor, tensor1.T)

tensor([[1.3188],
        [1.6417],
        [2.4417],
        [1.6000],
        [1.0753],
        [1.2226],
        [1.7071]])

### 4.Set the random seed to 0 and do 2 & 3 over again

In [7]:
torch.manual_seed(0)

X = torch.rand(7, 7)
Y = torch.rand(1, 7)

Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [8]:
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [16]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f'Device: {device}')

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [17]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
max = torch.max(tensor_C)
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
argmax = torch.argmax(tensor_C)
argmin = torch.argmin(tensor_C)
argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [21]:
torch.manual_seed(7)

tensor_D = torch.rand(1, 1, 1, 10)
tensor_E = tensor_D.squeeze()

tensor_D, tensor_D.shape, tensor_E, tensor_E.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))